name: Auto Update Toolforge New

on:
  push:
    branches:
      - main
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Test workspace
        run: |
          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE" # /home/runner/work/svg_translate/svg_translate # ls -al

      - name: Copy files to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: 22
          source: "./"
          target: "~/wikihelper_temp"
          rm: true

      - name: Deploy on Toolforge
        uses: appleboy/ssh-action@v1.2.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: 22
          request_pty: true
          script_stop: true
          key: ${{ secrets.KEY }}
          script: |
            become lyan bash -lc "
              rm -rf ~/WikiHelper &&
              cp -r /mnt/nfs/labstore-secondary-tools-home/${{ secrets.USERNAME }}/wikihelper_temp ~/WikiHelper &&
              chmod -R 770 ~/WikiHelper &&
              cp -rf ~/WikiHelper/web_sh/*.sh ~/web_sh -v &&
              cp -rf ~/WikiHelper/src/* ~/www/python/src/ -v &&
              rm -rf ~/WikiHelper &&
              echo \"Updated on: $(date '+%Y-%m-%d %H:%M:%S')\" > ~/update_from_github &&
              toolforge-jobs run pipup --image python3.11 --command "~/web_sh/pip.sh" --wait &&
              toolforge-webservice python3.11 stop &&
              toolforge-webservice python3.11 start &&
              echo ''
            "
            rm -rf wikihelper_temp
